from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Optional

import numpy as np
import OpenImageIO as oiio
import torch

MAX_FRAMES = 100_000

# Matches a printf-style frame specifier such as %04d or %d.
_FRAME_TOKEN_RE = re.compile(r'%\d*d')

_OIIO_BIT_DEPTHS: dict[str, oiio.TypeDesc] = {
    "half (16-bit)": oiio.HALF,
    "float (32-bit)": oiio.FLOAT,
}

_OIIO_COMPRESSIONS: dict[str, str] = {
    "ZIP": "zip",
    "PIZ": "piz",
    "DWAB": "dwab",
}

# Attributes set explicitly by writer format options; never overwritten by carried metadata.
_SKIP_METADATA_KEYS: frozenset[str] = frozenset({
    "compression",
    "openexr:chunkCount",
    "openexr:maxSamplesPerPixel",
    "openexr:roundingMode",
    "openexr:dwaCompressionLevel",
    "openexr:multiView",
})

# AOV channel-name groups, per EXR_REQUIREMENTS.md's convention table. Channels are always
# addressed by name, never index — OIIO does not preserve write order and reorders channels
# on read (see lib/CLAUDE.md "AOV Channel Handling").
CHANNELS_BEAUTY: tuple[str, ...] = ("R", "G", "B")
CHANNELS_ALPHA: tuple[str, ...] = ("A",)
CHANNELS_NORMAL: tuple[str, ...] = ("N.X", "N.Y", "N.Z")
CHANNELS_NORMAL_WORLD: tuple[str, ...] = ("Nw.X", "Nw.Y", "Nw.Z")
CHANNELS_DEPTH: tuple[str, ...] = ("Z",)

AOV_CHANNELS: dict[str, tuple[str, ...]] = {
    "normal": CHANNELS_NORMAL,
    "normal_world": CHANNELS_NORMAL_WORLD,
    "depth": CHANNELS_DEPTH,
}

# normal_raw has no dotted-channel or sibling-file convention (see the part-name
# convention below) — it exists only to carry a normals-like EXR part whose camera/world
# space this repo does not try to determine. Zero-filled at (H,W,3), like the other
# normal groups, when absent.
AOV_GROUP_WIDTH: dict[str, int] = {**{k: len(v) for k, v in AOV_CHANNELS.items()}, "normal_raw": 3}
AOV_KEYS: tuple[str, ...] = (*AOV_CHANNELS.keys(), "normal_raw")

# Fixed suffix convention matching ComfyUI_Harmonize/tests/generate_synthetic_exr.py exactly.
AOV_SUFFIXES: dict[str, str] = {
    "normal": "_AOV_Normals",
    "normal_world": "_AOV_NormalsWorld",
    "depth": "_AOV_Depth",
}

AOV_LAYOUTS: frozenset[str] = frozenset({"Multichannel", "Separate Files"})

# Part-name-keyed AOV convention: a true multi-part EXR where every part uses generic
# R/G/B channel names, and the AOV's identity is carried only by the EXR part `name`
# attribute. Confirmed against a real Flame render whose AOVs were imported from another
# DCC (Cinema 4D) rather than generated by Flame itself, so the dotted layer.channel
# convention above doesn't apply to that data at all — see lib/CLAUDE.md "AOV Channel
# Handling". Empty string disables lookup for that AOV. There is no default part name for
# camera-space normals or world-space normals, since no real file has demonstrated one —
# the single ambiguous "normals" part in the one file investigated maps to normal_raw,
# not NORMAL/NORMAL_WORLD, because this repo does not try to determine which space it's
# in; that's left to the consuming project.
DEFAULT_DEPTH_PART_NAME = "depth"
DEFAULT_NORMAL_RAW_PART_NAME = "normals"
DEFAULT_NORMAL_WORLD_PART_NAME = ""

# OIIO 3.x's EXR plugin treats "oiio:ColorSpace" as an enum tied to its internal OCIO
# built-in-config registry, not a free string: recognized names get silently renamed to
# their canonical form (e.g. "ACEScg" -> "lin_ap1_scene") and unrecognized ones (camera
# log profile names, show-specific LUT names) are silently DROPPED on write entirely.
# Verified against the installed OIIO 3.1.15 by round-tripping through actual EXR files.
# So carried-through colour-space identity is also stashed verbatim under this
# project-namespaced key, which OIIO does not special-case. Readers should prefer this
# key and fall back to "oiio:ColorSpace" for files this project didn't write itself.
COLOUR_SPACE_KEY = "oiio:ColorSpace"
COLOUR_SPACE_BACKUP_KEY = "openclip:ColorSpace"


def frame_path(path_pattern: str, frame_num: int) -> str:
    """Resolve a printf-style sequence pattern to a single frame's file path."""
    return path_pattern % frame_num if _FRAME_TOKEN_RE.search(path_pattern) else path_pattern


def read_sequence(
    path_pattern: str,
    start_frame: int,
    end_frame: int,
    load_alpha: bool,
) -> tuple[torch.Tensor, torch.Tensor, dict]:
    """Read a frame sequence. Returns (IMAGE [N,H,W,3], MASK [N,H,W], metadata).

    metadata is extracted from the first frame's OIIO extra_attribs. Thin wrapper around
    read_sequence_with_aovs() that drops the AOV dict, for callers that don't need AOVs.
    """
    images, masks, _aovs, metadata = read_sequence_with_aovs(path_pattern, start_frame, end_frame, load_alpha)
    return images, masks, metadata


def read_sequence_with_aovs(
    path_pattern: str,
    start_frame: int,
    end_frame: int,
    load_alpha: bool,
    depth_part_name: str = DEFAULT_DEPTH_PART_NAME,
    normal_world_part_name: str = DEFAULT_NORMAL_WORLD_PART_NAME,
    normal_raw_part_name: str = DEFAULT_NORMAL_RAW_PART_NAME,
) -> tuple[torch.Tensor, torch.Tensor, dict[str, Optional[torch.Tensor]], dict]:
    """Read a frame sequence plus AOV layers. Returns (IMAGE, MASK, aovs, metadata).

    aovs is {"normal": [N,H,W,3] | None, "normal_world": [N,H,W,3] | None,
    "depth": [N,H,W] | None, "normal_raw": [N,H,W,3] | None} -- always present with
    all four keys, but a key's *value* is None when that layer was never found in
    ANY frame of the sequence, so a consumer can tell "this AOV pass doesn't exist
    for this shot" apart from "it exists and is legitimately all-zero" (see
    ComfyUI_Harmonize's NormalsRouter/DepthRouter, the reason this distinction
    matters downstream). Whichever individual frames *within* a present AOV lack
    that frame's layer are still zero-filled -- None is only for "not found in any
    frame of the requested range," a per-sequence signal, not a per-frame one.

    "normal"/"normal_world"/"depth" are resolved, per AOV, in this order:
      1. Dotted layer.channel names (e.g. "N.X") on the beauty file's subimage 0 — the
         single-part multichannel convention EXR_REQUIREMENTS.md's synthetic fixtures use.
      2. A sibling '<name>_AOV_<Suffix>.####.ext' file (separate-file-per-AOV convention).
      3. depth_part_name / normal_world_part_name: an EXR part elsewhere in the beauty
         file whose `name` attribute matches (the real-world convention — see
         lib/CLAUDE.md "AOV Channel Handling"). Empty string disables this step.
      4. Zero-filled, and the AOV is marked not-found for this frame.
    "normal_raw" only has step 3 (via normal_raw_part_name) and step 4 — it carries a
    normals-like part whose camera/world space this repo does not try to determine;
    downstream space labelling is left to the consuming project.
    """
    n_frames = end_frame - start_frame + 1
    if n_frames <= 0:
        raise ValueError(f"start_frame ({start_frame}) must be <= end_frame ({end_frame})")
    if n_frames > MAX_FRAMES:
        raise RuntimeError(f"Frame count {n_frames} exceeds MAX_FRAMES={MAX_FRAMES}")

    images: list[torch.Tensor] = []
    masks: list[torch.Tensor] = []
    aov_frames: dict[str, list[np.ndarray]] = {key: [] for key in AOV_KEYS}
    found: dict[str, bool] = {key: False for key in AOV_KEYS}
    metadata: dict = {}

    sibling_patterns = {
        key: _aov_sibling_pattern(path_pattern, suffix) for key, suffix in AOV_SUFFIXES.items()
    }

    for i in range(n_frames):
        frame_num = start_frame + i
        filepath = frame_path(path_pattern, frame_num)
        image, mask, aov_groups, frame_meta = _read_frame(
            filepath, load_alpha, depth_part_name, normal_world_part_name, normal_raw_part_name
        )
        images.append(image)
        masks.append(mask)
        if i == 0:
            metadata = frame_meta

        h, w = image.shape[:2]
        for key in AOV_KEYS:
            group = aov_groups[key]
            if group is None and key in AOV_CHANNELS:
                sibling_path = frame_path(sibling_patterns[key], frame_num)
                group = _read_named_channels_if_exists(sibling_path, AOV_CHANNELS[key])
            if group is None:
                group = np.zeros((h, w, AOV_GROUP_WIDTH[key]), dtype=np.float32)
            else:
                found[key] = True
            if AOV_GROUP_WIDTH[key] == 1:
                group = group[:, :, 0]
            aov_frames[key].append(group)

    aovs: dict[str, Optional[torch.Tensor]] = {
        key: torch.from_numpy(np.stack(frames)) if found[key] else None
        for key, frames in aov_frames.items()
    }

    return torch.stack(images), torch.stack(masks), aovs, metadata


def write_sequence(
    path_pattern: str,
    images: torch.Tensor,
    masks: Optional[torch.Tensor],
    start_frame: int,
    file_format: str,
    exr_bit_depth: str = "half (16-bit)",
    exr_compression: str = "ZIP",
    metadata: Optional[dict] = None,
    aovs: Optional[dict[str, torch.Tensor]] = None,
    aov_layout: str = "Multichannel",
) -> None:
    """Write a frame sequence to disk.

    When metadata is provided it is written into each EXR header, with writer
    format settings (compression, etc.) applied last so they always win.

    aovs (optional) is a subset of {"normal": [N,H,W,3], "normal_world": [N,H,W,3],
    "depth": [N,H,W]}; entries whose value is None are ignored. aov_layout selects
    "Multichannel" (AOV channels appended to the same EXR as beauty) or
    "Separate Files" (one extra '<name>_AOV_<Suffix>.####.exr' per AOV, matching the
    fixed convention in AOV_SUFFIXES). AOVs require file_format="EXR".
    """
    n_frames = images.shape[0]
    if n_frames > MAX_FRAMES:
        raise RuntimeError(f"Frame count {n_frames} exceeds MAX_FRAMES={MAX_FRAMES}")
    if file_format == "EXR" and exr_bit_depth not in _OIIO_BIT_DEPTHS:
        raise ValueError(f"Unknown exr_bit_depth '{exr_bit_depth}'. Valid: {list(_OIIO_BIT_DEPTHS)}")
    if file_format == "EXR" and exr_compression not in _OIIO_COMPRESSIONS:
        raise ValueError(f"Unknown exr_compression '{exr_compression}'. Valid: {list(_OIIO_COMPRESSIONS)}")

    aovs = {k: v for k, v in (aovs or {}).items() if v is not None}
    if aovs:
        if file_format != "EXR":
            raise ValueError(f"AOV output requires file_format='EXR', got '{file_format}'")
        if aov_layout not in AOV_LAYOUTS:
            raise ValueError(f"Unknown aov_layout '{aov_layout}'. Valid: {sorted(AOV_LAYOUTS)}")

    sibling_patterns = (
        {key: _aov_sibling_pattern(path_pattern, AOV_SUFFIXES[key]) for key in aovs}
        if aovs and aov_layout == "Separate Files" else {}
    )

    for i in range(n_frames):
        frame_num = start_frame + i
        filepath = path_pattern % frame_num
        mask = masks[i] if masks is not None else None
        inline_aovs = {k: v[i] for k, v in aovs.items()} if aovs and aov_layout == "Multichannel" else None
        _write_frame(filepath, images[i], mask, file_format, exr_bit_depth, exr_compression, metadata, aovs=inline_aovs)

        if aovs and aov_layout == "Separate Files":
            for key, tensor in aovs.items():
                aov_filepath = sibling_patterns[key] % frame_num
                _write_exr(aov_filepath, _as_hwc(tensor[i].numpy()), AOV_CHANNELS[key], exr_bit_depth, exr_compression, metadata)


# --- private helpers ---


def _as_hwc(arr: np.ndarray) -> np.ndarray:
    """Promote a (H,W) single-channel array to (H,W,1)."""
    return arr[:, :, None] if arr.ndim == 2 else arr


def _aov_sibling_pattern(path_pattern: str, suffix: str) -> str:
    """Insert an AOV suffix into a beauty path pattern's stem.

    'shot.%04d.exr' -> 'shot_AOV_Normals.%04d.exr' (frame-token form)
    'shot.exr'      -> 'shot_AOV_Normals.exr'      (static single-image form, see
                        openclip_xml.py's Flame encoding="file" case)
    """
    m = _FRAME_TOKEN_RE.search(path_pattern)
    if m:
        head = path_pattern[:m.start()]
        sep = "."
        if head.endswith("."):
            head = head[:-1]
        else:
            sep = ""
        return f"{head}{suffix}{sep}{path_pattern[m.start():]}"
    p = Path(path_pattern)
    return str(p.with_name(f"{p.stem}{suffix}{p.suffix}"))


def _extract_named_channels(pixels: np.ndarray, channelnames, names: tuple[str, ...]) -> Optional[np.ndarray]:
    """Pull named channels from an already-decoded (H,W,C) array, in `names` order.

    Returns None if any requested name is absent — a channel group is all-or-nothing,
    never partially filled.
    """
    try:
        indices = [channelnames.index(n) for n in names]
    except ValueError:
        return None
    return pixels[:, :, indices]


def _extract_frame_metadata(spec) -> dict:
    result = {}
    for attr in spec.extra_attribs:
        try:
            result[attr.name] = attr.value
        except Exception:
            pass
    return result


def _read_frame(
    filepath: str,
    load_alpha: bool,
    depth_part_name: str = DEFAULT_DEPTH_PART_NAME,
    normal_world_part_name: str = DEFAULT_NORMAL_WORLD_PART_NAME,
    normal_raw_part_name: str = DEFAULT_NORMAL_RAW_PART_NAME,
) -> tuple[torch.Tensor, torch.Tensor, dict[str, Optional[np.ndarray]], dict]:
    """Read one frame's beauty/alpha/AOV data.

    Beauty, alpha, and the dotted-channel AOV convention are always read from subimage 0
    only — never merged across an EXR's other parts, since a real multi-part file's other
    parts (depth/normals/Cryptomatte) were found to just reuse the generic R/G/B channel
    names, making a channel-name merge across parts both wrong (indistinguishable
    duplicate names) and wasteful (a heavy Cryptomatte part would get decoded for no
    reason). See lib/CLAUDE.md "AOV Channel Handling".

    The part-name convention (depth_part_name/normal_world_part_name/
    normal_raw_part_name) then looks at the file's other subimages/parts, if any,
    decoding only ones whose EXR part `name` attribute matches one of those three
    targets — an unmatched part (e.g. Cryptomatte) is never pixel-decoded.
    """
    inp = oiio.ImageInput.open(str(filepath))
    if not inp:
        raise FileNotFoundError(f"OIIO could not open: {filepath}")

    spec0 = inp.spec()
    pixels0 = inp.read_image(oiio.FLOAT)
    if pixels0 is None:
        inp.close()
        raise RuntimeError(f"{filepath}: OIIO read_image returned None")
    pixels0 = np.asarray(pixels0, dtype=np.float32)
    metadata = _extract_frame_metadata(spec0)
    h, w = pixels0.shape[:2]
    channelnames0 = spec0.channelnames

    beauty = _extract_named_channels(pixels0, channelnames0, CHANNELS_BEAUTY)
    if beauty is None:
        inp.close()
        raise RuntimeError(f"{filepath}: missing required R/G/B channel(s); found channels {channelnames0}")
    image = torch.from_numpy(beauty)

    if load_alpha:
        alpha = _extract_named_channels(pixels0, channelnames0, CHANNELS_ALPHA)
        mask = torch.from_numpy(alpha[:, :, 0]) if alpha is not None else torch.zeros(h, w, dtype=torch.float32)
    else:
        mask = torch.zeros(h, w, dtype=torch.float32)

    aov_groups: dict[str, Optional[np.ndarray]] = {
        key: _extract_named_channels(pixels0, channelnames0, names) for key, names in AOV_CHANNELS.items()
    }
    aov_groups["normal_raw"] = None

    part_targets = {
        name: key
        for name, key in (
            (depth_part_name, "depth"),
            (normal_world_part_name, "normal_world"),
            (normal_raw_part_name, "normal_raw"),
        )
        if name
    }
    if part_targets:
        subimage = 1
        while inp.seek_subimage(subimage, 0):
            spec = inp.spec()
            subimage += 1
            part_name = spec.get_string_attribute("name", "") or spec.get_string_attribute("oiio:subimagename", "")
            key = part_targets.get(part_name)
            if key is None or aov_groups.get(key) is not None:
                continue
            pixels = inp.read_image(oiio.FLOAT)
            if pixels is None:
                continue
            pixels = np.asarray(pixels, dtype=np.float32)
            if pixels.shape[:2] != (h, w):
                continue
            if key == "depth":
                # Real-world depth parts store a replicated scalar across R/G/B (confirmed
                # empirically against a real Flame render) — channel 0 carries it.
                aov_groups["depth"] = pixels[:, :, 0:1]
            else:
                aov_groups[key] = pixels[:, :, :3]
    inp.close()

    return image, mask, aov_groups, metadata


def _read_named_channels_if_exists(filepath: str, names: tuple[str, ...]) -> Optional[np.ndarray]:
    """Best-effort read of named channels from a sibling AOV file. None if the file is
    missing, unreadable, or doesn't carry all the requested channel names — an absent
    sibling is not an error, the caller zero-fills."""
    if not os.path.exists(filepath):
        return None
    inp = oiio.ImageInput.open(str(filepath))
    if not inp:
        return None
    spec = inp.spec()
    pixels = inp.read_image(oiio.FLOAT)
    inp.close()
    if pixels is None:
        return None
    pixels = np.asarray(pixels, dtype=np.float32)
    return _extract_named_channels(pixels, spec.channelnames, names)


def _write_exr(
    filepath: str,
    pixels: np.ndarray,
    names: tuple[str, ...],
    exr_bit_depth: str,
    exr_compression: str,
    metadata: Optional[dict],
) -> None:
    height, width, nchannels = pixels.shape
    dtype = _OIIO_BIT_DEPTHS[exr_bit_depth]
    spec = oiio.ImageSpec(width, height, nchannels, dtype)
    spec.channelnames = tuple(names)
    if metadata:
        for key, value in metadata.items():
            if key not in _SKIP_METADATA_KEYS:
                try:
                    spec[key] = value
                except Exception:
                    pass
        if COLOUR_SPACE_KEY in metadata:
            # Verbatim backup — see COLOUR_SPACE_BACKUP_KEY's module-level comment.
            try:
                spec.attribute(COLOUR_SPACE_BACKUP_KEY, oiio.TypeString, str(metadata[COLOUR_SPACE_KEY]))
            except Exception:
                pass
    # Writer format settings are applied last so they always override carried metadata.
    spec["compression"] = _OIIO_COMPRESSIONS[exr_compression]
    pixels_write = np.ascontiguousarray(pixels, dtype=np.float32)
    _write_image_file(filepath, spec, pixels_write)


def _write_image_file(filepath: str, spec, pixels_write: np.ndarray) -> None:
    out = oiio.ImageOutput.create(filepath)
    if not out:
        raise RuntimeError(f"OIIO could not create output for: {filepath}")
    if not out.open(filepath, spec):
        raise RuntimeError(f"OIIO failed to open for writing: {filepath}")
    if not out.write_image(pixels_write):
        out.close()
        err = out.geterror()
        raise RuntimeError(f"OIIO write_image failed for: {filepath} - {err}")
    out.close()


def _write_frame(
    filepath: str,
    image: torch.Tensor,
    mask: Optional[torch.Tensor],
    file_format: str,
    exr_bit_depth: str,
    exr_compression: str,
    metadata: Optional[dict] = None,
    aovs: Optional[dict[str, torch.Tensor]] = None,
) -> None:
    channels = [image.numpy()]
    names = list(CHANNELS_BEAUTY)
    if mask is not None:
        channels.append(mask.unsqueeze(-1).numpy())
        names.append(CHANNELS_ALPHA[0])
    if aovs:
        for key, tensor in aovs.items():
            channels.append(_as_hwc(tensor.numpy()))
            names.extend(AOV_CHANNELS[key])
    pixels = np.concatenate(channels, axis=-1)

    if file_format == "EXR":
        _write_exr(filepath, pixels, tuple(names), exr_bit_depth, exr_compression, metadata)
    else:
        height, width = pixels.shape[:2]
        spec = oiio.ImageSpec(width, height, pixels.shape[-1], oiio.UINT8)
        pixels_write = np.ascontiguousarray((np.clip(pixels, 0.0, 1.0) * 255).astype(np.uint8))
        _write_image_file(filepath, spec, pixels_write)
